frontend:
  replicaCount: 1
  image: "nazarito0/fullstack-frontend:latest"

backend:
  replicaCount: 1
  image: "nazarito0/fullstack-backend:latest"

db:
  replicaCount: 1
  image: "postgres:16-alpine"

resources: {}