frontend:
  replicaCount: 2
  image: "nazarito0/fullstack-frontend:17"

backend:
  replicaCount: 1
  image: "nazarito0/fullstack-backend:17"

db:
  replicaCount: 1
  image: "postgres:16-alpine"

resources: {}