apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true" # ОБОВ'ЯЗКОВО для роботи (.*)
spec:
  rules:
  - host: frontend.com
    http:
      paths:
      # Шлях для API (має бути ПЕРШИМ, щоб перехоплювати /api)
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      # Шлях для фронтенду
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "mychart.fullname" . }}-frontend-service
            port:
              number: 80