apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: frontend.com
    http:
      paths:
      - path: /()(.*)  # $1 - порожньо, $2 - все інше (наприклад, /index.html)
        pathType: Prefix
        backend:
          service:
            name: {{ include "mychart.fullname" . }}-frontend-service
            port:
              number: 80
      - path: /api(/|$)(.*) # $1 - це (/|$), $2 - це все після /api/ (наприклад, "users")
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000