apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring # ОБОВ'ЯЗКОВО той самий неймспейс, де Grafana
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp2-helm-grafana
            port:
              number: 80